### ISSUE TITLE
parallax nonfunction

### ISSUE THREAD

**Issue by sebastianr415** [SebastianR415/final-countdown#3]
i added a parallax to my page for fun but my images are showing up can anybody review

**Comment by robaguilera** [comment]
Hey bro, so the fix is to remove the `/` from the image file path.
So change this `src="/IMG/outside-lands-2.jpeg"` to `src="IMG/outside-lands-2.jpeg` for all the images in your carousel section.
Here's an article that explains the difference between `/IMG` and `IMG` when trying to resolve file paths. https://www.w3schools.com/html/html_filepaths.asp

**Comment by sebastianr415** [comment]
hey bro, my carousel is working but parallax imgs isn't starting at line 165 to 172

**Comment by robaguilera** [comment]
Oh gotcha, must be something with my computer. Your carousel doesn't show up for me. For your parallax your CSS is correct. I think it's the value you're passing to the URL CSS property. Looks like the browser can't read it. Try downloading the image instead. So `background-image: url('../IMG/your-image.jpeg')`.

Also, you want to avoid relying on a random external party that you don't control for something like an image. If they fail obviously your image will be broken.

<img width="337" alt="Screen Shot 2022-05-09 at 9 01 14 AM" src="https://user-images.githubusercontent.com/5676808/167450349-a843d57a-da25-4c69-acc6-b4ec00471dc4.png">
